package com.mir00r.practiceApacheCamel.domains.challengequestions.models.rsa;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.10
 * 2024-10-28T16:59:47.761+08:00
 * Generated source version: 3.3.10
 *
 */
@WebService(targetNamespace = "http://ws.csd.rsa.com", name = "AdaptiveAuthenticationInterface")
@XmlSeeAlso({ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.761+08:00", comments = "Apache CXF 3.3.10")
public interface AdaptiveAuthenticationInterface {

    @WebMethod(action = "rsa:query:Query")
    @RequestWrapper(localName = "query", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.QueryResponse")
    @WebResult(name = "queryReturn", targetNamespace = "http://ws.csd.rsa.com")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.761+08:00")
    public com.sde.mobiusgateway.wsdl2java.rsa.QueryResponse2 query(

        @WebParam(name = "request", targetNamespace = "http://ws.csd.rsa.com")
        com.sde.mobiusgateway.wsdl2java.rsa.QueryRequest request
    ) throws AdaptiveAuthenticationSoapFault;

    @WebMethod(action = "rsa:analyze:Analyze")
    @RequestWrapper(localName = "analyze", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.Analyze")
    @ResponseWrapper(localName = "analyzeResponse", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.AnalyzeResponse")
    @WebResult(name = "analyzeReturn", targetNamespace = "http://ws.csd.rsa.com")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.761+08:00")
    public com.sde.mobiusgateway.wsdl2java.rsa.AnalyzeResponse2 analyze(

        @WebParam(name = "request", targetNamespace = "http://ws.csd.rsa.com")
        com.sde.mobiusgateway.wsdl2java.rsa.AnalyzeRequest request
    ) throws AdaptiveAuthenticationSoapFault;

    @WebMethod(action = "rsa:authenticate:Authenticate")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.AuthenticateResponse")
    @WebResult(name = "authenticateReturn", targetNamespace = "http://ws.csd.rsa.com")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.761+08:00")
    public com.sde.mobiusgateway.wsdl2java.rsa.AuthenticateResponse2 authenticate(

        @WebParam(name = "request", targetNamespace = "http://ws.csd.rsa.com")
        com.sde.mobiusgateway.wsdl2java.rsa.AuthenticateRequest request
    ) throws AdaptiveAuthenticationSoapFault;

    @WebMethod(action = "rsa:notify:Notify")
    @RequestWrapper(localName = "notify", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.Notify")
    @ResponseWrapper(localName = "notifyResponse", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.NotifyResponse")
    @WebResult(name = "notifyReturn", targetNamespace = "http://ws.csd.rsa.com")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.761+08:00")
    public com.sde.mobiusgateway.wsdl2java.rsa.NotifyResponse2 notify(

        @WebParam(name = "request", targetNamespace = "http://ws.csd.rsa.com")
        com.sde.mobiusgateway.wsdl2java.rsa.NotifyRequest request
    ) throws AdaptiveAuthenticationSoapFault;

    @WebMethod(action = "rsa:queryauthstatus:QueryAuthStatus")
    @RequestWrapper(localName = "queryAuthStatus", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.QueryAuthStatus")
    @ResponseWrapper(localName = "queryAuthStatusResponse", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.QueryAuthStatusResponse")
    @WebResult(name = "queryAuthStatusReturn", targetNamespace = "http://ws.csd.rsa.com")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.761+08:00")
    public com.sde.mobiusgateway.wsdl2java.rsa.QueryAuthStatusResponse2 queryAuthStatus(

        @WebParam(name = "request", targetNamespace = "http://ws.csd.rsa.com")
        com.sde.mobiusgateway.wsdl2java.rsa.QueryAuthStatusRequest request
    ) throws AdaptiveAuthenticationSoapFault;

    @WebMethod(action = "rsa:createuser:CreateUser")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.CreateUserResponse")
    @WebResult(name = "createUserReturn", targetNamespace = "http://ws.csd.rsa.com")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.761+08:00")
    public com.sde.mobiusgateway.wsdl2java.rsa.CreateUserResponse2 createUser(

        @WebParam(name = "request", targetNamespace = "http://ws.csd.rsa.com")
        com.sde.mobiusgateway.wsdl2java.rsa.CreateUserRequest request
    ) throws AdaptiveAuthenticationSoapFault;

    @WebMethod(action = "rsa:challenge:Challenge")
    @RequestWrapper(localName = "challenge", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.Challenge")
    @ResponseWrapper(localName = "challengeResponse", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.ChallengeResponse")
    @WebResult(name = "challengeReturn", targetNamespace = "http://ws.csd.rsa.com")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.761+08:00")
    public com.sde.mobiusgateway.wsdl2java.rsa.ChallengeResponse2 challenge(

        @WebParam(name = "request", targetNamespace = "http://ws.csd.rsa.com")
        com.sde.mobiusgateway.wsdl2java.rsa.ChallengeRequest request
    ) throws AdaptiveAuthenticationSoapFault;

    @WebMethod(action = "rsa:udpateuser:UpdateUser")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ws.csd.rsa.com", className = "com.sde.mobiusgateway.wsdl2java.rsa.UpdateUserResponse")
    @WebResult(name = "updateUserReturn", targetNamespace = "http://ws.csd.rsa.com")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.761+08:00")
    public com.sde.mobiusgateway.wsdl2java.rsa.UpdateUserResponse2 updateUser(

        @WebParam(name = "request", targetNamespace = "http://ws.csd.rsa.com")
        com.sde.mobiusgateway.wsdl2java.rsa.UpdateUserRequest request
    ) throws AdaptiveAuthenticationSoapFault;
}
