package com.mir00r.practiceApacheCamel.domains.challengequestions.models.rsa;

import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.10
 * 2024-10-28T16:59:47.801+08:00
 * Generated source version: 3.3.10
 *
 */
@WebServiceClient(name = "AdaptiveAuthentication",
                  wsdlLocation = "file:/C:/Users/sdarmd/Desktop/SDE/CBS/sde-biz-affin-mobius-gateway/sde-biz-affin-mobius-gateway-service/src/main/resources/wsdl/RSA/AdaptiveAuthentication_1.wsdl",
                  targetNamespace = "http://ws.csd.rsa.com")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00", comments = "Apache CXF 3.3.10")
public class AdaptiveAuthentication extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public final static QName SERVICE = new QName("http://ws.csd.rsa.com", "AdaptiveAuthentication");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public final static QName AdaptiveAuthentication = new QName("http://ws.csd.rsa.com", "AdaptiveAuthentication");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/sdarmd/Desktop/SDE/CBS/sde-biz-affin-mobius-gateway/sde-biz-affin-mobius-gateway-service/src/main/resources/wsdl/RSA/AdaptiveAuthentication_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdaptiveAuthentication.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/sdarmd/Desktop/SDE/CBS/sde-biz-affin-mobius-gateway/sde-biz-affin-mobius-gateway-service/src/main/resources/wsdl/RSA/AdaptiveAuthentication_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public AdaptiveAuthentication(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public AdaptiveAuthentication(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public AdaptiveAuthentication() {
        super(WSDL_LOCATION, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public AdaptiveAuthentication(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public AdaptiveAuthentication(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public AdaptiveAuthentication(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AdaptiveAuthenticationInterface
     */
    @WebEndpoint(name = "AdaptiveAuthentication")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public AdaptiveAuthenticationInterface getAdaptiveAuthentication() {
        return super.getPort(AdaptiveAuthentication, AdaptiveAuthenticationInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdaptiveAuthenticationInterface
     */
    @WebEndpoint(name = "AdaptiveAuthentication")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2024-10-28T16:59:47.801+08:00")
    public AdaptiveAuthenticationInterface getAdaptiveAuthentication(WebServiceFeature... features) {
        return super.getPort(AdaptiveAuthentication, AdaptiveAuthenticationInterface.class, features);
    }

}
